### ISSUE TITLE
Problem running on Windows 7 (Python 2.7)

### ISSUE THREAD

**Issue by pedrodj** [D4Vinci/One-Lin3r#1]
***
$ python One_Lin3r.py -h
Traceback (most recent call last):
  File "One_Lin3r.py", line 3, in <module>
    from Core import Cli
  File "E:\Python27\One-Lin3r-master\Core\Cli.py", line 5, in <module>
    from . import utils,db
  File "E:\Python27\One-Lin3r-master\Core\utils.py", line 81
    print(s, end='')
                ^
SyntaxError: invalid syntax
***

Installed as described on your Installation Notes: any fix?

Thank you :)

**Comment by D4Vinci** [comment]
Fixed it now check it out and reopen if the issue continues.

**Comment by pedrodj** [comment]
No seems fixed ;)

Thank you mate :)
