### ISSUE TITLE
Ubuntu 18.04 ImportError: cannot import name 'CompleteStyle'

### ISSUE THREAD

**Issue by udpsec** [D4Vinci/One-Lin3r#19]
pip3 install One-Lin3r; success
But running the program display:
Traceback (most recent call last):
  File "/usr/local/bin/one-lin3r", line 7, in <module>
    from one_lin3r.main import main
  File "/usr/local/lib/python3.6/dist-packages/one_lin3r/main.py", line 3, in <module>
    from .core import Cli
  File "/usr/local/lib/python3.6/dist-packages/one_lin3r/core/Cli.py", line 6, in <module>
    from . import utils,db
  File "/usr/local/lib/python3.6/dist-packages/one_lin3r/core/utils.py", line 5, in <module>
    from prompt_toolkit.shortcuts import CompleteStyle, prompt
ImportError: cannot import name 'CompleteStyle'

**Comment by Zerx0r** [comment]
I solved this problem with the command bellow:

`pip3 install prompt-toolkit --force-reinstall`

**Comment by udpsec** [comment]
> I solved this problem with the command below:
> 
> `pip3 install prompt-toolkit --force-reinstall`

thanks

**Comment by naami2004** [comment]
> I solved this problem with the command below:
> 
> `pip3 install prompt-toolkit --force-reinstall`

Thank you, that fixed my problem :)
