### ISSUE TITLE
error launching One-Lin3r

### ISSUE THREAD

**Issue by jepunband** [D4Vinci/One-Lin3r#24]
Installation method:

    pip install one-lin3r
    one-lin3r -h

$:/usr/local/bin# ./one-lin3r -h

Traceback (most recent call last):
  File "./one-lin3r", line 5, in <module>
    from one_lin3r.main import main
  File "/usr/local/lib/python2.7/dist-packages/one_lin3r/main.py", line 3, in <module>
    from .core import Cli
  File "/usr/local/lib/python2.7/dist-packages/one_lin3r/core/Cli.py", line 143
    print(Search_parser.format_help(), end="")
                                          ^
SyntaxError: invalid syntax

**Comment by D4Vinci** [comment]
run it with python version 3 as stated!
